---
- hosts: localhost

  tasks:
    - name: Gather vmware host facts
      vmware_host_facts:
        hostname: 192.168.128.218
        username: root
        password: r3dh4t1!
        validate_certs: false
      register: host_facts
      delegate_to: localhost