---
- hosts: localhost
  tasks:
    - name: Gather vmware host facts
      vmware_host_facts:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
      register: host_facts
      delegate_to: localhost

    - debug:
        var: host_facts