---
- hosts: localhost
  vars_files:
  - vars.yml
  tasks:
    - name: Gather vmware host facts from vCenter
      vmware_host_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
      register: host_facts
      delegate_to: localhost

    - debug:
        var: host_facts